---
apiVersion: v1
kind: Namespace
metadata:
  name: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true